#!/bin/sh

if ! [ -d /run/ConsoleKit ]; then
	mkdir -p -m0755 /run/ConsoleKit
fi

# wait for services if available
for service in cgmanager dbus; do
  if [ -e "/service/${service}" ]; then
    sv check "/service/${service}" >/dev/null || exit 1
  fi
done

exec 2>&1
exec console-kit-daemon --no-daemon
