#!/bin/sh

if ! [ -d /run/ConsoleKit ]; then
	mkdir -p -m0755 /run/ConsoleKit
fi

# wait for services if available
if [ -e /var/service/cgmanager ]; then
	sv check cgmanager >/dev/null || exit 1
fi
if [ -e /var/service/dbus ]; then
	sv check dbus >/dev/null || exit 1
fi

exec 2>&1
exec console-kit-daemon --no-daemon
