#!/bin/sh

# should be start after services like dbus, networkmanager
for service in dbus networkmanager NetworkManager; do
  if [ -e "/var/service/${service}" ]; then
	sv check "$service" > /dev/null || exit 1
  fi
done

exec 2>&1
tlp init start || exit 1
exec chpst -b tlp pause
