#!/bin/sh

[ -r conf ] && . ./conf

[ ! -d /var/run/mysql ] && mkdir -p /var/run/mysql
chown "${MYSQLD_USER:-mysql}":"${MYSQLD_USER:-mysql}" /var/run/mysql

exec 2>&1
exec chpst -u "${MYSQLD_USER:-mysql}":"${MYSQLD_USER:-mysql}" mysqld \
	--defaults-file="${MYSQLD_CONF:-/etc/my.cnf}" \
	"${MY_OPTS:---skip-networking}" \
	--user="${MYSQLD_USER:-mysql}"
